<?php

/**
 * @file
 * @author Bob Hutchinson http://drupal.org/user/52366
 * @copyright GNU GPL
 *
 * Defines getlocations fields type.
 */

define('GETLOCATIONS_FIELDS_PATH', drupal_get_path('module', 'getlocations_fields'));

/**
 * Implements hook_help().
 */
function getlocations_fields_help($path, $arg) {
  switch ($path) {
    case 'admin/help#getlocations':
      $output = '<p>' . t('Provides a getlocations geocoder field type.') . '</p>';
      return $output;
  }
}


/**
 * Implements hook_init().
 */
function getlocations_fields_init() {
  module_load_include('inc', 'getlocations_fields', 'getlocations_fields.functions');
  module_load_include('inc', 'getlocations_fields', 'getlocations_fields.theme');
}

/**
 * Implements hook_menu().
 */
function getlocations_fields_menu() {
  $items = array();

  $items['admin/config/services/getlocations_fields'] = array(
    'title' => 'Getlocations fields',
    'description' => 'Configure Getlocations fields',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('getlocations_fields_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'getlocations_fields.admin.inc',
  );

  // ajax callback to fetch country code from full name
  $items['getlocations_fields/countryinfo'] = array(
    'page callback' => 'getlocations_fields_countryinfo',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  // autocomplete paths
  $items['getlocations_fields/country_autocomplete'] = array(
    'page callback' => 'getlocations_fields_country_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['getlocations_fields/province_autocomplete'] = array(
    'page callback' => 'getlocations_fields_province_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['getlocations_fields/city_autocomplete'] = array(
    'page callback' => 'getlocations_fields_city_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  if (module_exists('smart_ip')) {
    $items['getlocations_fields/smart_ip'] = array(
      'page callback' => 'getlocations_fields_smart_ip',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );
  }

  return $items;

}

/**
 * Implements hook_views_api().
 */
function getlocations_fields_views_api() {
  return array(
    'api' => 3,
    'path' => GETLOCATIONS_FIELDS_PATH . '/views',
  );
}

/**
 * Implements hook_field_info().
 * Define Field API field types.
 *
 * @return
 *   An array whose keys are field type names and whose values are arrays
 *   describing the field type.
 */
function getlocations_fields_field_info() {

  $info = getlocations_fields_field_info_defaults();
  return $info;

}

/**
 * Implements hook_field_validate().
 * Validate this module's field data.
 *
 * This hook gives us a chance to validate content that's in our
 * field. We're really only interested in the $items parameter, since
 * it holds arrays representing content in the field we've defined.
 *
 * @param $entity_type
 *   The type of $entity.
 * @param $entity
 *   The entity for the operation.
 * @param $field
 *   The field structure for the operation.
 * @param $instance
 *   The instance structure for $field on $entity's bundle.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   $entity->{$field['field_name']}[$langcode], or an empty array if unset.
 * @param $errors
 *   The array of errors (keyed by field name, language code, and delta) that
 *   have already been reported for the entity.
 */
function getlocations_fields_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {

  if (! empty($items)) {
    $required = $instance['required'];
    $cardinality = $field['cardinality'];
    $count_items = count($items);
    $fieldnames = array(
      'name' => t('Name'),
      'street' => t('Street'),
      'additional' => t('Additional'),
      'city' => t('City/Town'),
      'province' => t('Province/State/County'),
      'postal_code' => t('Post code/Zip code'),
      'country' => t('Country'),
    );
    $item_count = 0;
    foreach ($items AS $delta => $item) {
      if ($item['active']) {
        if (isset($item['delete_location']) && $item['delete_location']) {
          return;
        }
        // unlimited so don't error on the last one
        if ($cardinality == -1 && $item_count == ($count_items - 1)) {
          return;
        }
        if ($required && empty($item['latitude']) && empty($item['longitude'])) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'latlon_empty',
            'message' => t('Latitude and Longitude empty'),
            'field_name' => $field['field_name'],
            'lang' => $langcode,
            'delta' => $delta,
          );
        }
        if (isset($item['getlocations_required']) && $item['getlocations_required']) {
          $requireds = explode(',', $item['getlocations_required']);
          foreach ($requireds AS $id) {
            if (isset($item[$id]) && empty($item[$id])) {
              $errors[$field['field_name']][$langcode][$delta][] = array(
                'error' => 'field_required_' . $id,
                'message' => t('The %tt field is required', array('%tt' => $fieldnames[$id])),
              );
            }
          }
        }
      }
      $item_count++;
    }
  }
}

/**
 * Implements hook_field_insert().
 * Define custom insert behavior for this module's field types.
 *
 * @param $entity_type
 *   The type of $entity.
 * @param $entity
 *   The entity for the operation.
 * @param $field
 *   The field structure for the operation.
 * @param $instance
 *   The instance structure for $field on $entity's bundle.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   $entity->{$field['field_name']}[$langcode], or an empty array if unset.
 */
function getlocations_fields_field_insert($entity_type, $entity, $field, $instance, $langcode, &$items) {

  if (!empty($items)) {
    foreach ($items AS $key => $item) {
      if ( empty($item['latitude']) || empty($item['longitude']) ) {
        unset($items[$key]);
      }
    }

    $criteria = array();
    if ($entity_type == 'node') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'vid' => $entity->vid,
        'nid' => $entity->nid,
      );
    }
    elseif ($entity_type == 'user' || $entity_type == 'profile2') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'uid' => $entity->uid,
      );
    }
    elseif ($entity_type == 'comment') {
      //
      $criteria = array(
        'field_name' => $field['field_name'],
        'cid' => $entity->cid,
      );
    }
    elseif ($entity_type == 'taxonomy_term') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'tid' => $entity->tid,
      );
    }
    if (! empty($criteria)) {
      $items = getlocations_fields_save_locations($items, $criteria, 'insert');
    }
  }
}

/**
 * Implements hook_field_update().
 * Define custom update behavior for this module's field types.
 *
 * @param $entity_type
 *   The type of $entity.
 * @param $entity
 *   The entity for the operation.
 * @param $field
 *   The field structure for the operation.
 * @param $instance
 *   The instance structure for $field on $entity's bundle.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   $entity->{$field['field_name']}[$langcode], or an empty array if unset.
 */
function getlocations_fields_field_update($entity_type, $entity, $field, $instance, $langcode, &$items) {

  if (!empty($items)) {

    $criteria = array();
    if ($entity_type == 'node') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'vid' => $entity->vid,
        'nid' => $entity->nid,
      );
    }
    elseif ($entity_type == 'user' || $entity_type == 'profile2') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'uid' => $entity->uid,
      );
    }
    elseif ($entity_type == 'comment') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'cid' => $entity->cid,
      );
    }
    elseif ($entity_type == 'taxonomy_term') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'tid' => $entity->tid,
      );
    }
    if (! empty($criteria)) {
      // look for delete_location in $items
      if (! $instance['required'] || ($instance['required'] && count($items) > 1 )) {
        foreach ($items AS $key => $item) {
          if (isset($item['delete_location']) && $item['delete_location'] > 0) {
            getlocations_fields_delete_record($items[$key], $criteria);
            unset($items[$key]);
          }
        }
      }
      $items = getlocations_fields_save_locations($items, $criteria, 'update');
    }
  }

}

/**
 * Implements hook_field_delete().
 * Define custom delete behavior for this module's field types.
 *
 * @param $entity_type
 *   The type of $entity.
 * @param $entity
 *   The entity for the operation.
 * @param $field
 *   The field structure for the operation.
 * @param $instance
 *   The instance structure for $field on $entity's bundle.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   $entity->{$field['field_name']}[$langcode], or an empty array if unset.
 */
function getlocations_fields_field_delete($entity_type, $entity, $field, $instance, $langcode, &$items) {

  if (!empty($items)) {
    $criteria = array();
    if ($entity_type == 'node') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'nid' => $entity->nid,
        'vid' => $entity->vid,
      );
    }
    elseif ($entity_type == 'user' || $entity_type == 'profile2') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'uid' => $entity->uid,
      );
    }
    elseif ($entity_type == 'comment') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'cid' => $entity->cid,
      );
    }
    elseif ($entity_type == 'taxonomy_term') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'tid' => $entity->tid,
      );
    }
    if (! empty($criteria)) {
      $items = getlocations_fields_save_locations($items, $criteria, 'delete');
    }
  }
}

/**
 * Implements hook_field_delete_revision().
 * Define custom revision delete behavior for this module's field types.
 *
 * @param $entity_type
 *   The type of $entity.
 * @param $entity
 *   The entity for the operation.
 * @param $field
 *   The field structure for the operation.
 * @param $instance
 *   The instance structure for $field on $entity's bundle.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   $entity->{$field['field_name']}[$langcode], or an empty array if unset.
 */
function getlocations_fields_field_delete_revision($entity_type, $entity, $field, $instance, $langcode, &$items) {

  if (! empty($items)) {
    if ($entity_type == 'node') {
      $criteria = array(
        'field_name' => $field['field_name'],
        'vid' => $entity->vid,
      );
      $items = getlocations_fields_save_locations($items, $criteria, 'delete_revision');
    }
  }
}

/**
 * Implements hook_field_load().
 * Define custom load behavior for this module's field types.
 * http://api.drupal.org/api/drupal/modules--field--field.api.php/function/hook_field_load/7
 *
 * @param $entity_type
 *   The type of $entity.
 * @param $entities
 *   Array of entities being loaded, keyed by entity ID.
 * @param $field
 *   The field structure for the operation.
 * @param $instances
 *   Array of instance structures for $field for each entity, keyed by entity ID.
 * @param $langcode
 *   The language code associated with $items.
 * @param $items
 *   Array of field values already loaded for the entities, keyed by entity ID.
 *   Store your changes in this parameter (passed by reference).
 * @param $age
 *   FIELD_LOAD_CURRENT to load the most recent revision for all fields, or
 *   FIELD_LOAD_REVISION to load the version indicated by each entity.
 */
function getlocations_fields_field_load($entity_type, $entities, $field, $instances, $langcode, &$items, $age) {

  foreach ($entities as $id => $entity) {
    foreach ($items[$id] as $delta => $item) {
      $location = array();
      // Load the location if it exists.
      // If we are previewing a new node it will not.
      if (! empty($item['glid'])) {
        $location = getlocations_fields_load_location($item['glid']);
      }
      // Combine the item with the location loaded from the database.
      // This will allow $item to display in the case of previewing a node.
      $items[$id][$delta] = array_merge($location, $item);
    }
  }

}

/**
 * Implements hook_field_settings_form().
 * Add settings to a field settings form.
 *
 * Invoked from field_ui_field_settings_form() to allow the module defining the
 * field to add global settings (i.e. settings that do not depend on the bundle
 * or instance) to the field settings form. If the field already has data, only
 * include settings that are safe to change.
 *
 * @todo: Only the field type module knows which settings will affect the
 * field's schema, but only the field storage module knows what schema
 * changes are permitted once a field already has data. Probably we need an
 * easy way for a field type module to ask whether an update to a new schema
 * will be allowed without having to build up a fake $prior_field structure
 * for hook_field_update_forbid().
 *
 * @param $field
 *   The field structure being configured.
 * @param $instance
 *   The instance structure being configured.
 * @param $has_data
 *   TRUE if the field already has data, FALSE if not.
 *
 * @return
 *   The form definition for the field settings.
 */
function getlocations_fields_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];
  if (empty($settings)) {
    $settings = getlocations_fields_field_info_defaults();
  }

  $form = array();

  $form += getlocations_fields_input_settings_form($settings);

  $form['mapwidth'] = getlocations_element_map_tf(
    t('Input form Map width'),
    $settings['mapwidth'],
    t('The width of a Google map, as a CSS length or percentage. Examples: <em>50px</em>, <em>5em</em>, <em>2.5in</em>, <em>95%</em>'),
    10,
    10,
    TRUE
  );
  $form['mapheight'] = getlocations_element_map_tf(
    t('Input form Map height'),
    $settings['mapheight'],
    t('The height of a Google map, as a CSS length or percentage. Examples: <em>50px</em>, <em>5em</em>, <em>2.5in</em>, <em>95%</em>'),
    10,
    10,
    TRUE
  );
  $form['latlong'] = getlocations_element_map_tf(
    t('Input form Map center'),
    $settings['latlong'],
    t('The default center coordinates of a Google map, expressed as a decimal latitude and longitude, separated by a comma. This must not be 0,0'),
    30,
    30,
    TRUE
  );
  // smart_ip latlon option
  if (module_exists('smart_ip')) {
    $form['use_smart_ip_latlon'] = getlocations_element_map_checkbox(
      t('Use Smart IP to set Latitude/Longitude'),
      $settings['use_smart_ip_latlon'],
      t('Use Smart IP module to set the default center coordinates.')
    );
  }
  else {
    $form['use_smart_ip_latlon'] = array('#type' => 'value', '#value' => 0);
  }
  // input form marker
  $markers = getlocations_get_marker_titles();
  $form['input_map_marker'] = getlocations_element_map_marker(
    t('Input form Map marker'),
    $markers,
    $settings['input_map_marker']
  );

  $form['zoom'] = getlocations_element_map_zoom(
    t('Zoom'),
    $settings['zoom'],
    t('The default zoom level of a Google map.')
  );

  $form += getlocations_map_display_options_form($settings, FALSE, FALSE);

  unset($form['#theme']);
  $form['#theme'] = 'getlocations_fields_field_settings_form';

  return $form;

# where to put it?
#      if ( empty($field['width']) || is_int($field['width']) || $field['width'] < 1 ) {
#        form_set_error($field['width'], t('Must be a positive number.'));
#      }

}

/**
 * Implements hook_field_is_empty().
 * Define what constitutes an empty item for a field type.
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 *
 * @param $item
 *   An item that may or may not be empty.
 * @param $field
 *   The field to which $item belongs.
 * @return
 *   TRUE if $field's type considers $item not to contain any data;
 *   FALSE otherwise.
 */
function getlocations_fields_field_is_empty($item, $field) {
  return FALSE;
}

/**
 * Implements hook_field_formatter_info().
 *
 * Declare information about a formatter.
 *
 * @return
 *   An array keyed by formatter name. Each element of the array is an associative
 *   array with these keys and values:
 *   - "label": The human-readable label for the formatter.
 *   - "field types": An array of field type names that can be displayed using
 *     this formatter.
 *
 * @see getlocations_fields_field_formatter_view()
 */
function getlocations_fields_field_formatter_info() {
  $formatters = array(
    'getlocations_fields_default' => array(
      'label' => t('Getlocations Field'),
      'field types' => array('getlocations_fields'),
      'settings' => getlocations_fields_field_formatter_info_defaults(),
    ),
  );
  return $formatters;
}

/**
 * Implements hook_field_formatter_view().
 * Build a renderable array for a field value.
 *
 * @param $entity_type
 *   The type of $entity.
 * @param $entity
 *   The entity being displayed.
 * @param $field
 *   The field structure.
 * @param $instance
 *   The field instance.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   Array of values for this field.
 * @param $display
 *   The display settings to use, as found in the 'display' entry of instance definitions.
 * @return
 *   A renderable array for the $items, as an array of child elements keyed
 *   by numeric indexes starting from 0.
 *
 * @see getlocations_fields_field_formatter_info()
 */
function getlocations_fields_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  drupal_add_css(GETLOCATIONS_FIELDS_PATH . '/getlocations_fields.css');

  $settings = $display['settings'];

  if (empty($settings)) {
    $settings = getlocations_fields_field_formatter_info_defaults();
  }

  // reset markers, in case there are any left from old method
  $getlocations_defaults = getlocations_defaults();
  $settings['node_map_marker'] = $getlocations_defaults['node_map_marker'];
  $settings['user_map_marker'] = $getlocations_defaults['user_map_marker'];
  $settings['vocabulary_map_marker'] = $getlocations_defaults['vocabulary_map_marker'];
  $settings['comment_map_marker'] = $getlocations_defaults['comment_map_marker'];
  $settings['term_map_marker'] = $getlocations_defaults['term_map_marker'];

  $field_name = '';
  if (isset($field['field_name'])) {
    $field_name = $field['field_name'];
  }
  $locations = array();
  $supported_entity_types = array('node', 'user', 'taxonomy_term', 'comment', 'profile2');

  $element = array();
  if (! in_array($entity_type, $supported_entity_types)) {
    return $element;
  }

  if ($entity_type == 'node') {
    $locations = getlocations_fields_load_locations($entity->vid, 'vid', $field_name);
    if (count($locations)) {

      $getlocations_node_marker = variable_get('getlocations_node_marker', array('enable' => 0));
      if ($getlocations_node_marker['enable']) {
        if ($types = getlocations_get_types()) {
          foreach ($types AS $type => $name) {
            $field_names = getlocations_get_fieldname2($type, $entity_type);
            foreach ($field_names AS $f_name) {
              if ( $field_name && $f_name == $field_name) {
                $mkey = 'node_marker__' . $type . '__' . $field_name;
                if (isset($settings[$mkey])) {
                  $settings['map_marker'] = $settings[$mkey];
                }
                else {
                  $settings['map_marker'] = (isset($getlocations_node_marker['content_type'][$type]['field_name'][$field_name]['map_marker']) ? $getlocations_node_marker['content_type'][$type]['field_name'][$field_name]['map_marker'] : $settings['node_map_marker']);
                }
              }
            }
          }
        }
      }
      else {
        $settings['map_marker'] = $settings['node_map_marker'];
      }

      // term marker. this will override node marker if there is one
      $settings['map_marker'] = getlocations_get_term_marker($entity->nid, $settings['map_marker']);
    }
  }
  elseif ($entity_type == 'taxonomy_term' && module_exists('taxonomy')) {
    $locations = getlocations_fields_load_locations($entity->tid, 'tid', $field_name);
    if (count($locations)) {
      $settings['map_marker'] = $settings['vocabulary_map_marker'];
      $getlocations_vocabulary_marker = variable_get('getlocations_vocabulary_marker', array('enable' => 0));
      if ($getlocations_vocabulary_marker['enable']) {
        if ($types = getlocations_get_vocabularies()) {
          foreach ($types AS $type => $name) {
            $f_name = getlocations_get_fieldname($type, $entity_type);
            if ($f_name == $field_name) {
              $mkey = 'vocabulary_marker_' . $field_name;
              if (isset($settings[$mkey])) {
                $settings['map_marker'] = $settings[$mkey];
              }
              else {
                $settings['map_marker'] = (isset($getlocations_vocabulary_marker['vocabulary'][$type]['map_marker']) ? $getlocations_vocabulary_marker['vocabulary'][$type]['map_marker'] : $settings['vocabulary_map_marker']);
              }
            }
          }
        }
      }
      else {
        $settings['map_marker'] = $settings['vocabulary_map_marker'];
      }
    }
  }
  elseif ($entity_type == 'user' || $entity_type == 'profile2') {
    $locations = getlocations_fields_load_locations($entity->uid, 'uid', $field_name);
    if (count($locations)) {
      $settings['map_marker'] = $settings['user_map_marker'];
    }
  }
  elseif ($entity_type == 'comment') {
    $locations = getlocations_fields_load_locations($entity->cid, 'cid', $field_name);
    if (count($locations)) {
      $settings['map_marker'] = $settings['comment_map_marker'];
    }
  }

  switch ($display['type']) {
    case 'getlocations_fields_default':
    if (count($locations)) {
#      foreach ($items as $delta => $item) {
#        $element[$delta] = array(
#          '#theme' => 'getlocations_fields_show',
#          '#locations' => $locations,
#          '#settings' => $settings,
#        );
#      }
      $element[0]  = array(
        '#theme' => 'getlocations_fields_show',
        '#locations' => $locations,
        '#settings' => $settings,
      );
    }
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_form().
 * Returns form elements for a formatter's settings.
 *
 * @param $field
 *   The field structure being configured.
 * @param $instance
 *   The instance structure being configured.
 * @param $view_mode
 *   The view mode being configured.
 * @param $form
 *   The (entire) configuration form array, which will usually have no use here.
 * @param $form_state
 *   The form state of the (entire) configuration form.
 *
 * @return
 *   The form elements for the formatter settings.
 */
function getlocations_fields_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  drupal_add_js(GETLOCATIONS_FIELDS_PATH . '/js/getlocations_fields_formatter.js');
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $getlocations_defaults = getlocations_defaults();
  $getlocations_fields_defaults = getlocations_fields_defaults();
  if (empty($settings)) {
    $settings = $getlocations_fields_defaults;
  }

  // $instance['entity_type'] contains node, user etc
  $entity_type = $instance['entity_type'];

  $element = array();

  // address display options
  $element += getlocations_fields_display_settings_form($settings);

  $element += getlocations_map_display_options_form($settings, FALSE);

  // markeraction
  $element['markeractiontype'] = getlocations_element_map_markeractiontype(
    $settings['markeractiontype']
  );
  $element['markeraction'] = getlocations_element_map_markeraction(
    $settings['markeraction']
  );

  unset($element['#theme']);
  $element['#theme'] = 'getlocations_fields_field_formatter_settings_form';

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 * Returns a short summary for the current formatter settings of an instance.
 *
 *
 * If an empty result is returned, the formatter is assumed to have no
 * configurable settings, and no UI will be provided to display a settings
 * form.
 *
 *   The field structure.
 * @param $instance
 *   The instance structure.
 * @param $view_mode
 *   The view mode for which a settings summary is requested.
 *
 * @return
 *   A string containing a short summary of the formatter settings.
 */
function getlocations_fields_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $entity_type = $instance['entity_type'];

  $summary = array();
  // map summary
  if ($settings['display_showmap']) {
    $summary[] = t('Show map: Yes');
    if ($settings['display_mapwidth'] && $settings['display_mapheight']) {
      $summary[] = t('Width: @w | Height: @h', array('@w' => $settings['display_mapwidth'], '@h' => $settings['display_mapheight']));
    }
    if ($settings['display_latlong']) {
      $summary[] = t('Show Latitude/Longitude: Yes');
    }
    if ($settings['display_dms']) {
      $summary[] = t('Show Latitude/Longitude in Degrees, minutes, seconds');
    }
    if ($settings['display_onemap']) {
      $summary[] = t('Show all locations on one map');
    }
    if ($settings['controltype']) {
      $summary[] = t('Zoom control type: @c', array('@c' => $settings['controltype']));
    }
    if ($settings['pancontrol']) {
      $summary[] = t('Show Pan control: Yes');
    }
    if ($settings['mtc']) {
      $summary[] = t('Map control type: @c', array('@c' => $settings['mtc']));
    }
    if ($settings['maptype']) {
      $summary[] = t('Default map type: @c', array('@c' => $settings['maptype']));
    }
    $types = array();
    foreach ($settings['baselayers'] AS $key => $value) {
      if ($value) {
        $types[] = $key;
      }
    }
    if (count($types)) {
      $m = implode(', ', $types);
      $summary[] = t('Enabled map types: @m', array('@m' => $m));
    }

    $types = array();
    foreach ($settings['behavior'] AS $key => $value) {
      if ($value) {
        $types[] = $key;
      }
    }
    if (count($types)) {
      foreach ($types AS $type) {
        if ($type == 'scale') {
          $summary[] = t('Show scale: Yes');
        }
        elseif ($type == 'overview') {
          $summary[] = t('Show overview map: Yes');
        }
        elseif ($type == 'scrollwheel') {
          $summary[] = t('Enable scrollwheel zooming: Yes');
        }
      }
    }

    if ($settings['draggable']) {
      $summary[] = t('Enable dragging the map: Yes');
    }
    if ($settings['streetview_show']) {
      $summary[] = t('Show streetview button: Yes');
    }

    $info_display = array();
    if ($settings['trafficinfo']) {
      $info_display[] = t('Traffic');
    }
    if ($settings['bicycleinfo']) {
      $info_display[] = t('Bicycling');
    }
    if ($settings['transitinfo']) {
      $info_display[] = t('Transit');
    }
    if ($settings['panoramio_show']) {
      $info_display[] = t('Panoramio');
    }
    if ($settings['poi_show']) {
      $info_display[] = t('Points of Interest');
    }
    if ($settings['transit_show']) {
      $info_display[] = t('Transit Points');
    }
    if (count($info_display)) {
      $summary[] = t("Enabled information layers:") . '<br />' . implode(', ', $info_display);
    }

    if ($entity_type == 'user' || $entity_type == 'profile2') {
      if ($settings['user_map_marker']) {
        $summary[] = t('User map marker: @c', array('@c' => $settings['user_map_marker']));
      }
    }
    elseif ($entity_type == 'taxonomy_term') {
      if ($settings['vocabulary_map_marker']) {
        $summary[] = t('Vocabulary map marker: @c', array('@c' => $settings['vocabulary_map_marker']));
      }
    }
    elseif ($entity_type == 'comment') {
      if ($settings['comment_map_marker']) {
        $summary[] = t('Comment map marker: @c', array('@c' => $settings['comment_map_marker']));
      }
    }
    else {
      if ($settings['node_map_marker']) {
        $summary[] = t('Content map marker: @c', array('@c' => $settings['node_map_marker']));
      }
    }

    if ($settings['map_backgroundcolor']) {
      $summary[] = t('Map background color: @c', array('@c' => $settings['map_backgroundcolor']));
    }

    if ($settings['markeraction'] > 0) {
      if ($settings['markeraction'] == 1) {
        $msg = t('InfoWindow');
      }
      elseif ($settings['markeraction'] == 2) {
        $msg = t('InfoBubble');
      }
      else {
        $msg = t('Link');
      }
      if ($settings['markeractiontype'] == 2) {
        $msg2 = t('Mouse over');
      }
      else {
        $msg2 = t('Click');
      }
      $summary[] = t('Marker action: @a on @b', array('@a' => $msg, '@b' => $msg2));
    }
    $summary[] = t('Zoom level: @z', array('@z' => $settings['nodezoom']));
  }
  else {
    $summary[] = t('Show map: No');
    if ($settings['display_maplink']) {
      $summary[] = t('Show map link: Yes');
    }
  }
  // address summary
  $address_display = array();
  if ($settings['display_name']) {
    $address_display[] = t("Name");
  }
  if ($settings['display_street']) {
    $address_display[] = t("Street");
  }
  if ($settings['display_additional']) {
    $address_display[] = t("Additional");
  }
  if ($settings['display_city']) {
    $address_display[] = t("City");
  }
  if ($settings['display_province']) {
    $address_display[] = t("Province");
  }
  if ($settings['display_postal_code']) {
    $address_display[] = t("Postcode");
  }
  if ($settings['display_country']) {
    $address_display[] = t("Country");
  }
  if (count($address_display)) {
    $summary[] = t("Show in Address:") . '<br />' . implode(', ', $address_display);
  }
  if ($settings['country_full']) {
    $summary[] = t('Display full country name: Yes');
  }

  return implode('<br />', $summary);

}

/**
 * Implements hook_field_widget_info().
 * Expose Field API widget types.
 *
 * @return
 *   An array describing the widget types implemented by the module.
 */
function getlocations_fields_field_widget_info() {

  $getlocations_fields_defaults = getlocations_fields_defaults();

  return array(
    'getlocations_fields' => array(
      'label' => t('Geocoder'),
      'field types' => array('getlocations_fields'),
      'settings' => array(
        'country'                    => $getlocations_fields_defaults['country'],
        'use_country_dropdown'       => $getlocations_fields_defaults['use_country_dropdown'],
        'province_autocomplete'      => $getlocations_fields_defaults['province_autocomplete'],
        'city_autocomplete'          => $getlocations_fields_defaults['city_autocomplete'],
        'use_address'                => $getlocations_fields_defaults['use_address'],
        'input_address_width'        => $getlocations_fields_defaults['input_address_width'],
        'input_name_width'           => $getlocations_fields_defaults['input_name_width'],
        'input_street_width'         => $getlocations_fields_defaults['input_street_width'],
        'input_additional_width'     => $getlocations_fields_defaults['input_additional_width'],
        'input_city_width'           => $getlocations_fields_defaults['input_city_width'],
        'input_province_width'       => $getlocations_fields_defaults['input_province_width'],
        'input_postal_code_width'    => $getlocations_fields_defaults['input_postal_code_width'],
        'input_country_width'        => $getlocations_fields_defaults['input_country_width'],
        'input_latitude_width'       => $getlocations_fields_defaults['input_latitude_width'],
        'input_longitude_width'      => $getlocations_fields_defaults['input_longitude_width'],
        'input_name_weight'          => $getlocations_fields_defaults['input_name_weight'],
        'input_street_weight'        => $getlocations_fields_defaults['input_street_weight'],
        'input_additional_weight'    => $getlocations_fields_defaults['input_additional_weight'],
        'input_city_weight'          => $getlocations_fields_defaults['input_city_weight'],
        'input_province_weight'      => $getlocations_fields_defaults['input_province_weight'],
        'input_postal_code_weight'   => $getlocations_fields_defaults['input_postal_code_weight'],
        'input_country_weight'       => $getlocations_fields_defaults['input_country_weight'],
        'input_latitude_weight'      => $getlocations_fields_defaults['input_latitude_weight'],
        'input_longitude_weight'     => $getlocations_fields_defaults['input_longitude_weight'],
        'input_name_required'        => $getlocations_fields_defaults['input_name_required'],
        'input_street_required'      => $getlocations_fields_defaults['input_street_required'],
        'input_additional_required'  => $getlocations_fields_defaults['input_additional_required'],
        'input_city_required'        => $getlocations_fields_defaults['input_city_required'],
        'input_province_required'    => $getlocations_fields_defaults['input_province_required'],
        'input_postal_code_required' => $getlocations_fields_defaults['input_postal_code_required'],
        'input_country_required'     => $getlocations_fields_defaults['input_country_required'],
        'per_item_marker'            => $getlocations_fields_defaults['per_item_marker'],
      ),
#      'behaviour' => array(
#        'multiple values' => FIELD_BEHAVIOR_DEFAULT
#        #'multiple values' => FIELD_BEHAVIOR_CUSTOM
#      ),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 * Return the form for a single field widget.
 *
 * @param $form
 *   The form structure where widgets are being attached to. This might be a
 *   full form structure, or a sub-element of a larger form.
 * @param $form_state
 *   An associative array containing the current state of the form.
 * @param $field
 *   The field structure.
 * @param $instance
 *   The field instance.
 * @param $langcode
 *   The language associated with $items.
 * @param $items
 *   Array of default values for this field.
 * @param $delta
 *   The order of this item in the array of subelements (0, 1, 2, etc).
 * @param $element
 *   A form element array containing basic properties for the widget.
 * @return
 *   The form elements for a single widget for this field.
 */
function getlocations_fields_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  switch ($instance['widget']['type']) {
    case 'getlocations_fields':

      // is this real or a demo in settings
      $active = TRUE;
      if (empty($element['#entity'])) {
        $active = FALSE;
      }

      $element['#delta'] = $delta;

      $field_name = '';
      if (isset($field['field_name'])) {
        $field_name = $field['field_name'];
        $items[$delta]['field_name'] = $field_name;
      }

      $cardinality = $field['cardinality'];
      $settings = $field['settings'];
      $m = getlocations_fields_getmap($settings, $active);
      $map = $m[0];
      $mapid = $m[1];

      // Wrap in a fieldset for single fields
      if ($cardinality == 1) {
        $element['#type'] = 'fieldset';
        $element['#collapsible'] = TRUE;
        $element['#collapsed'] = FALSE;
      }
      // delete location
      if (isset($items[$delta]['glid']) && $items[$delta]['glid'] > 0 ) {
        $element['glid'] = array(
          '#type' => 'value',
          '#value' => $items[$delta]['glid'],
        );
        if ( ! $instance['required']) {
          $element['delete_location'] = array(
            '#type' => 'checkbox',
            '#title' => t('Delete'),
            '#default_value' => FALSE,
            '#description' => t('Check this box to delete this location.'),
          );
        }
      }
      // search field
      if ($settings['use_address']) {
        $element['address'] = array(
          '#type' => 'textfield',
          '#default_value' => (isset($items[$delta]['address']) ? $items[$delta]['address'] : ''),
          '#size' => $settings['input_address_width'],
          '#attributes' => array('id' => ($active ? 'getlocations_address_' . $mapid : 'getlocations_default_address'), 'placeholder' => t('Enter an address')),
          '#title' => t('Search'),
          '#description' => t('Start typing an address and select from the dropdown.'),
          '#field_name' => $instance['field_name'],
          '#maxlength' => 255,
        );
        if ($instance['required']) {
          if ($active) {
            $element['address']['#required'] = TRUE;
          }
          else {
            $element['address']['#field_suffix'] = t('(Required)');
          }
        }
      } // TODO add a message, required form or not

      // smart_ip
      if ($active) {
        if (module_exists('smart_ip') && $settings['use_smart_ip_button']) {
          $element['smart_ip_button'] = array(
            '#markup' => '',
          );
          if (! empty($settings['input_smart_ip_button_weight'])) {
            $element['smart_ip_button']['#weight'] = $settings['input_smart_ip_button_weight'];
          }
        }
        if ($settings['use_geolocation_button']) {
          $element['geolocation_button'] = array(
            '#markup' => '',
          );
          if (! empty($settings['input_geolocation_button_weight'])) {
            $element['geolocation_button']['#weight'] = $settings['input_geolocation_button_weight'];
          }
        }
      }
      // loop over these as they are all the same
      $required = array();
      $inputarr = array(
        'name' => t('Name'),
        'street' => t('Street'),
        'additional' => t('Additional'),
        'city' => t('City/Town'),
        'province' => t('Province/State/County'),
        'postal_code' => t('Post code/Zip code'),
      );
      foreach ($inputarr AS $id => $title) {
        if ($settings['input_' . $id . '_required'] == 4) {
          // hidden form
          $element[$id] = array(
            '#type' => 'hidden',
            '#value' => (isset($items[$delta][$id]) ? $items[$delta][$id] : ''),
            '#attributes' => array('id' => 'getlocations_' . $id . '_' . $mapid),
          );
        }
        elseif ($settings['input_' . $id . '_required'] == 3) {
          $element[$id] = array(
            '#type' => 'hidden',
            '#value' => (isset($items[$delta][$id]) ? $items[$delta][$id] : ''),
            '#attributes' => array('id' => 'getlocations_' . $id . '_' . $mapid),
          );
          $element[$id . '_display'] = array(
            '#markup' => (isset($items[$delta][$id]) ? $items[$delta][$id] : ''),
          );
        }
        else {
          $element[$id] = array(
            '#type' => 'textfield',
            '#default_value' => (isset($items[$delta][$id]) ? htmlspecialchars_decode($items[$delta][$id], ENT_QUOTES) : ''),
           '#size' => $settings['input_' . $id . '_width'],
            '#attributes' => array('id' => 'getlocations_' . $id . '_' . $mapid),
            '#title' => $title,
            '#maxlength' => 255,
          );
          // autocomplete for province
          if ($id == 'province' && $settings['province_autocomplete'] ) {
            $element[$id]['#autocomplete_path'] = 'getlocations_fields/province_autocomplete';
          }
          // autocomplete for city
          elseif ($id == 'city' && $settings['city_autocomplete'] ) {
            $element[$id]['#autocomplete_path'] = 'getlocations_fields/city_autocomplete';
          }
        }
        if ($settings['input_' . $id . '_required'] == 2) {
          $element[$id]['#disabled'] = TRUE;
        }
        elseif ($settings['input_' . $id . '_required'] == 1) {
          if ($active) {
            if ($cardinality == -1) {
              # needs to be replaced with a 'fake'
              $required[] = $id;
            }
            else {
              $element[$id]['#required'] = TRUE;
            }
          }
          else {
            $element[$id]['#field_suffix'] = t('(Required)');
          }
        }
        if (! empty($settings['input_' . $id . '_weight'])) {
          $element[$id]['#weight'] = $settings['input_' . $id . '_weight'];
        }
      }

      // country
      if ($settings['restrict_by_country'] && $settings['search_country']) {
        $default_country_value = (isset($items[$delta]['country']) && $items[$delta]['country'] ? $items[$delta]['country'] : $settings['search_country']);
        $default_country_value_long = getlocations_get_country_name($default_country_value);
        $element['country'] = array(
          '#type' => 'hidden',
          '#value' => $default_country_value,
          '#attributes' => array('id' => 'getlocations_country_' . $mapid),
        );
        $element['country_display'] = array(
          '#markup' => $default_country_value_long,
        );
      }
      else {
        $default_country_value = (isset($items[$delta]['country']) && $items[$delta]['country'] ? $items[$delta]['country'] : $settings['country']);
        $default_country_value_long = $default_country_value;
        if ($default_country_value && drupal_strlen($default_country_value) == 2) {
          $default_country_value_long = getlocations_get_country_name($default_country_value);
        }
        if ($settings['input_country_required'] == 4) {
          // hidden form
          $element['country'] = array(
            '#type' => 'hidden',
            '#value' => $default_country_value,
            '#attributes' => array('id' => 'getlocations_country_' . $mapid),
          );
        }
        elseif ($settings['input_country_required'] == 3) {
          // hidden form
          $element['country'] = array(
            '#type' => 'hidden',
            '#value' => $default_country_value,
            '#attributes' => array('id' => 'getlocations_country_' . $mapid),
          );
          $element['country_display'] = array(
            '#markup' => $default_country_value_long,
          );
        }
        else {
          if ($settings['use_country_dropdown'] == 1) {
            $only_continents = '';
            $only_countries = '';
            if (module_exists('countries')) {
              $only_continents = (isset($settings['only_continents']) ? $settings['only_continents'] : '');
              $only_countries =  (isset($settings['only_countries']) ? $settings['only_countries'] : '');
            }
            $countries = getlocations_get_countries_list(TRUE, $only_continents, $only_countries);
            $countries = array_merge(array('' => t('---Please select a country---')), $countries);
            $element['country'] = array(
              '#type' => 'select',
              '#default_value' => $default_country_value,
              '#options' => $countries,
              '#title' => t('Country'),
              '#attributes' => array('id' => 'getlocations_country_' . $mapid),
            );
          }
          else {
            $element['country'] = array(
              '#type' => 'textfield',
              '#default_value' => $default_country_value_long,
              '#autocomplete_path' => ($settings['use_country_dropdown'] == 2 ? 'getlocations_fields/country_autocomplete' : ''),
              '#size' => $settings['input_country_width'],
              '#attributes' => array('id' => 'getlocations_country_' . $mapid),
              '#title' => t('Country'),
              '#maxlength' => 255,
            );
          }
          if ($settings['input_country_required'] == 2) {
            $element['country']['#disabled'] = TRUE;
          }
          elseif ($settings['input_country_required'] == 1) {
            if ($active) {
              if ($cardinality == -1) {
                $required[] = 'country';
              }
              else {
                $element['country']['#required'] = TRUE;
              }
            }
            else {
              $element['country']['#field_suffix'] = t('(Required)');
            }
          }
        }
        if (! empty($settings['input_country_weight'])) {
          $element['country']['#weight'] = $settings['input_country_weight'];
        }

      }

      // per_item_marker
      if ($settings['per_item_marker']) {
        $markers = getlocations_get_marker_titles();
        $markers = array_merge(array('' => t('Default')), $markers);
        $element['marker'] = getlocations_element_map_marker(
          t('Map marker'),
          $markers,
          (isset($items[$delta]['marker']) ? $items[$delta]['marker'] : '')
        );
        if (! empty($settings['input_marker_weight'])) {
          $element['marker']['#weight'] = $settings['input_marker_weight'];
        }
      }
      else {
        $element['marker'] = array(
          '#type' => 'value',
          '#value' => '',
        );
      }

      // geobutton
      if ($active) {
        if ($settings['use_address'] < 2) {
          $element['geobutton'] = array(
            '#markup' => '',
          );
          if (! empty($settings['input_geobutton_weight'])) {
            $element['geobutton']['#weight'] = $settings['input_geobutton_weight'];
          }
        }
        $element['mapid'] = array(
          '#type' => 'value',
          '#value' => $mapid,
        );
      }
      // map
      $element['map'] = array(
        '#markup' => $map,
      );
      if (! empty($settings['input_map_weight'])) {
        $element['map']['#weight'] = $settings['input_map_weight'];
      }
      // latitude
      $element['latitude'] = array(
        '#type' => 'textfield',
        '#default_value' => isset($items[$delta]['latitude']) ? $items[$delta]['latitude'] : '',
        '#size' => $settings['input_latitude_width'],
        '#attributes' => array('id' => 'getlocations_latitude_' . $mapid),
        '#title' => t('Latitude'),
        '#maxlength' => 20,
      );
      if (! empty($settings['input_latitude_weight'])) {
        $element['latitude']['#weight'] = $settings['input_latitude_weight'];
      }
      // longitude
      $element['longitude'] = array(
        '#type' => 'textfield',
        '#default_value' => isset($items[$delta]['longitude']) ? $items[$delta]['longitude'] : NULL,
        '#size' => $settings['input_longitude_width'],
        '#attributes' => array('id' => 'getlocations_longitude_' . $mapid),
        '#title' => t('Longitude'),
        '#maxlength' => 20,
      );
      if (! empty($settings['input_longitude_weight'])) {
        $element['longitude']['#weight'] = $settings['input_longitude_weight'];
      }

      $element['active'] = array(
        '#type' => 'value',
        '#value' => $active,
      );

      if (count($required)) {
        $element['getlocations_required'] = array(
          '#type' => 'value',
          '#value' => implode(',', $required),
        );
      }

      unset($element['#theme']);
      $element['#theme'] = 'getlocations_fields_field_widget_form';
    break;
  }

  return $element;

}

/**
 * Implements hook_field_widget_error().
 * Flag a field-level validation error.
 *
 * @param $element
 *   An array containing the form element for the widget. The error needs to be
 *   flagged on the right sub-element, according to the widget's internal structure.
 * @param $error
 *   An associative array, as returned by getlocations_fields_field_validate().
 * @param $form
 *   The form structure where field elements are attached to. This might be a
 *   full form structure, or a sub-element of a larger form.
 * @param $form_state
 *   An associative array containing the current state of the form.
 */
function getlocations_fields_field_widget_error($element, $error, $form, &$form_state) {

  switch ($error['error']) {
    case 'latlon_empty':
      unset($form_state['values'][$error['field_name']][$error['lang']][$error['delta']]);
      break;
    case 'field_required_name':
      form_error($element['name'], $error['message']);
      break;
    case 'field_required_street':
      form_error($element['street'], $error['message']);
      break;
    case 'field_required_additional':
      form_error($element['additional'], $error['message']);
      break;
    case 'field_required_city':
      form_error($element['city'], $error['message']);
      break;
    case 'field_required_province':
      form_error($element['province'], $error['message']);
      break;
    case 'field_required_postal_code':
      form_error($element['postal_code'], $error['message']);
      break;
    case 'field_required_country':
      form_error($element['country'], $error['message']);
      break;

  }
}

/**
 * input map
 * @param $settings
 *    The map settings
 *
 * @param $active
 *    Determine wether this is from the edit form or just a demo on the settings
 */
function getlocations_fields_getmap($settings, $active) {

  $getlocations_defaults = getlocations_defaults();

  // we do not want these on an input map
  $getlocations_defaults['panoramio_use']   = 0;
  $getlocations_defaults['panoramio_show']  = 0;
  $getlocations_defaults['trafficinfo']     = 0;
  $getlocations_defaults['bicycleinfo']     = 0;
  $getlocations_defaults['transitinfo']     = 0;
  $getlocations_defaults['markeraction']    = 0;
  $getlocations_defaults['streetview_show'] = 0;
  $getlocations_defaults['weather_use']     = 0;
  $getlocations_defaults['weather_show']    = 0;

  if ($active) {
    $getlocations_defaults['places'] = 1;
  }
  $getlocations_defaults['latlong'] = $settings['latlong'];
  if (module_exists('smart_ip') && $settings['use_smart_ip_latlon']) {
    $lla = getlocations_fields_smart_ip_get();
    if ($lla && is_array($lla)) {
      $ll = $lla['latitude'] . ',' . $lla['longitude'];
      if (getlocations_latlon_check($ll)) {
        $getlocations_defaults['latlong'] = $ll;
      }
    }
  }
  $getlocations_defaults['zoom']                = $settings['zoom'];
  $getlocations_defaults['controltype']         = $settings['controltype'];
  $getlocations_defaults['pancontrol']          = $settings['pancontrol'];
  $getlocations_defaults['mtc']                 = $settings['mtc'];
  $getlocations_defaults['maptype']             = $settings['maptype'];
  $getlocations_defaults['baselayers']          = $settings['baselayers'];
  $getlocations_defaults['behavior']            = $settings['behavior'];
  $getlocations_defaults['draggable']           = $settings['draggable'];
  $getlocations_defaults['input_map_marker']    = $settings['input_map_marker'];
  $getlocations_defaults['use_address']         = $settings['use_address'];
  $getlocations_defaults['map_backgroundcolor'] = $settings['map_backgroundcolor'];
  #$getlocations_defaults['use_jsapi']       = $settings['use_geolocation_button'];

  $mapid = getlocations_setup_map($getlocations_defaults);
  drupal_add_css(GETLOCATIONS_FIELDS_PATH . '/getlocations_fields.css');

  if ($active) {
    $getlocations_fields_paths = variable_get('getlocations_fields_paths', array('getlocations_fields_path' => GETLOCATIONS_FIELDS_PATH . '/js/getlocations_fields.js'));
    $js_opts = array();
    $js_opts['weight'] = $getlocations_defaults['getlocations_js_weight'] + 10;
    $js_opts['type'] = 'file';
    drupal_add_js($getlocations_fields_paths['getlocations_fields_path'], $js_opts);
    $settings['nodezoom'] = $getlocations_defaults['nodezoom'];
    getlocations_fields_js_settings_do($settings, $mapid);

    $latlons = array();
  }
  else {
    // demo mode
    $latlons = array();
    $getlocations_defaults['nodezoom'] = $getlocations_defaults['zoom'];
  }

  $minmaxes = '';
  getlocations_js_settings_do($getlocations_defaults, $latlons, $minmaxes, $mapid, $active);

  $map = theme('getlocations_show', array('width' => $settings['mapwidth'] , 'height' => $settings['mapheight'] , 'defaults' => $getlocations_defaults, 'mapid' => $mapid, 'type' => '', 'node' => ''));

  return array($map, $mapid);
}

/**
 * Used by theme for display output.
 */
function getlocations_fields_getmap_show($settings, $lls = '', $minmaxes = '') {

  $getlocations_defaults = getlocations_defaults();
  $getlocations_defaults['controltype']           = $settings['controltype'];
  $getlocations_defaults['pancontrol']            = $settings['pancontrol'];
  $getlocations_defaults['mtc']                   = $settings['mtc'];
  $getlocations_defaults['maptype']               = $settings['maptype'];
  $getlocations_defaults['baselayers']            = $settings['baselayers'];
  $getlocations_defaults['behavior']              = $settings['behavior'];
  $getlocations_defaults['draggable']             = $settings['draggable'];
  $getlocations_defaults['streetview_show']       = $settings['streetview_show'];
  $getlocations_defaults['trafficinfo']           = $settings['trafficinfo'];
  $getlocations_defaults['trafficinfo_state']     = $settings['trafficinfo_state'];
  $getlocations_defaults['bicycleinfo']           = $settings['bicycleinfo'];
  $getlocations_defaults['bicycleinfo_state']     = $settings['bicycleinfo_state'];
  $getlocations_defaults['transitinfo']           = $settings['transitinfo'];
  $getlocations_defaults['transitinfo_state']     = $settings['transitinfo_state'];
  $getlocations_defaults['panoramio_show']        = $settings['panoramio_show'];
  $getlocations_defaults['panoramio_state']       = $settings['panoramio_state'];
  $getlocations_defaults['poi_show']              = $settings['poi_show'];
  $getlocations_defaults['transit_show']          = $settings['transit_show'];
  $getlocations_defaults['node_map_marker']       = $settings['node_map_marker'];
  $getlocations_defaults['user_map_marker']       = $settings['user_map_marker'];
  $getlocations_defaults['vocabulary_map_marker'] = $settings['vocabulary_map_marker'];
  $getlocations_defaults['comment_map_marker']    = $settings['comment_map_marker'];
  $getlocations_defaults['markeraction']          = $settings['markeraction'];
  $getlocations_defaults['markeractiontype']      = $settings['markeractiontype'];
  $getlocations_defaults['nodezoom']              = $settings['nodezoom'];
  $getlocations_defaults['weather_show']          = $settings['weather_show'];
  $getlocations_defaults['weather_state']         = $settings['weather_state'];
  $getlocations_defaults['weather_cloud']         = $settings['weather_cloud'];
  $getlocations_defaults['weather_cloud_state']   = $settings['weather_cloud_state'];
  $getlocations_defaults['map_backgroundcolor']   = $settings['map_backgroundcolor'];

  // not ideal but required for preview
  $getlocations_defaults['places'] = 1;

  // onemap
  if ($settings['display_onemap']) {
    $latlons = $lls;
  }
  else {
    $latlons[] = $lls;
  }

  $mapid = getlocations_setup_map($getlocations_defaults);

  getlocations_js_settings_do($getlocations_defaults, $latlons, $minmaxes, $mapid);
  return theme('getlocations_show', array('width' => $settings['display_mapwidth'], 'height' => $settings['display_mapheight'], 'defaults' => $getlocations_defaults, 'mapid' => $mapid, 'type' => '', 'node' => ''));
}

/**
 * @param array $locations
 *  An array of locations to be saved
 *
 * @param array $criteria
 *  Relationship information
 *
 * @param string $mode
 *  The action to be carried out
 *
 * @return array $locations
 *
 */
function getlocations_fields_save_locations($locations, $criteria, $mode) {

  if (isset($locations) && is_array($locations) && !empty($criteria) && is_array($criteria)) {

    foreach (array_keys($locations) as $key) {
      // remove empties
      if ( empty($locations[$key]['latitude']) && empty($locations[$key]['longitude'])) {
        unset($locations[$key]);
        continue;
      }

      if ($mode == 'insert') {
        if ( $locations[$key]['latitude'] && $locations[$key]['longitude']) {
          $result = getlocations_fields_insert_record($locations[$key], $criteria);
          if ($result) {
            $locations[$key]['glid'] = $result;
          }
          else {
            unset($locations[$key]);
            continue;
          }
        }
        else {
          unset($locations[$key]);
          continue;
        }
      }
      elseif ($mode == 'update') {
        $result = getlocations_fields_update_record($locations[$key], $criteria);
        if ($result && ! isset($locations[$key]['glid'])) {
          $locations[$key]['glid'] = $result;
        }
      }
      elseif ($mode == 'delete') {
        getlocations_fields_delete_record($locations[$key], $criteria);
        unset($locations[$key]);
      }
      elseif ($mode == 'delete_revision') {
        getlocations_fields_delete_revision_record($locations[$key], $criteria);
        unset($locations[$key]);
      }
    }
    return $locations;
  }
}

/**
 * Create a location
 * @param array $location
 *  The new location
 *
 * @param array $relations
 *  Relationship information
 *
 */
function getlocations_fields_insert_record($location, $relations) {

  $noaddress = t('Enter an address');
  if (! isset($location['address']) || $location['address'] == $noaddress) {
    $location['address'] = '';
  }
  if (empty($location['latitude']) && empty($location['longitude'])) {
    return FALSE;
  }
  $query = db_insert('getlocations_fields');
  $query->fields(array(
    'name' => getlocations_apoclean($location['name']),
    'street' => getlocations_apoclean($location['street']),
    'additional' => getlocations_apoclean($location['additional']),
    'city' => getlocations_apoclean($location['city']),
    'province' => getlocations_apoclean($location['province']),
    'postal_code' => getlocations_apoclean($location['postal_code']),
    'country' => check_plain($location['country']),
    'address' => getlocations_apoclean($location['address']),
    'latitude' => (float) $location['latitude'],
    'longitude' => (float) $location['longitude'],
    'marker' => ($location['marker'] ? $location['marker'] : '')
  ));
  $result = $query->execute();
  // $result should contain glid
  // new insert id
  if ($result) {
    $relations['glid'] = $result;
    getlocations_fields_insert_record_relations($relations);
    return $result;
  }
  return FALSE;
}

/**
 * Insert the relationship information
 * @param array $relations
 *
 */
function getlocations_fields_insert_record_relations($relations) {

  db_insert('getlocations_fields_entities')->fields($relations)->execute();

}

/**
 * Create a location
 * @param array $location
 *  The location
 *
 * @param array $relations
 *  Relationship information
 *
 */
function getlocations_fields_update_record($location, $relations) {

  if (! isset($location['glid'])) {
    // this record does not exist yet
    $result = getlocations_fields_insert_record($location, $relations);
    return $result;
  }

  $noaddress = t('Enter an address');
  if (! isset($location['address']) || $location['address'] == $noaddress) {
    $location['address'] = '';
  }
  if (empty($location['latitude']) && empty($location['longitude'])) {
    return FALSE;
  }
  $num_updated = db_update('getlocations_fields')
    ->fields(array(
      'name' => getlocations_apoclean($location['name']),
      'street' => getlocations_apoclean($location['street']),
      'additional' => getlocations_apoclean($location['additional']),
      'city' => getlocations_apoclean($location['city']),
      'province' => getlocations_apoclean($location['province']),
      'postal_code' => getlocations_apoclean($location['postal_code']),
      'country' => check_plain($location['country']),
      'address' => getlocations_apoclean($location['address']),
      'latitude' => (float) $location['latitude'],
      'longitude' => (float) $location['longitude'],
      'marker' => ($location['marker'] ? $location['marker'] : '')
    ))
    ->condition('glid', $location['glid'])
    ->execute();

  getlocations_fields_update_record_relations($relations, $location['glid']);
}

/**
 * @param array $relations
 *  Relationship information
 *
 * @param int $glid
 *  The location ID
 *
 */
function getlocations_fields_update_record_relations($relations, $glid) {

  $num_updated = db_update('getlocations_fields_entities')
    ->fields($relations)
    ->condition('glid', $glid)
    ->execute();
}

/**
 * Create a location
 * @param array $location
 *  The location
 *
 * @param array $relations
 *  Relationship information
 *
 */
function getlocations_fields_delete_record($location, $relations) {

  if (isset($location['glid'])) {
    db_delete('getlocations_fields')
      ->condition('glid', $location['glid'])
      ->execute();
    getlocations_fields_delete_record_relations($relations, $location['glid']);
  }

}

/**
 * @param array $relations
 *  Relationship information
 *
 * @param int $glid
 *  The location ID
 *
 */
function getlocations_fields_delete_record_relations($relations, $glid) {

  db_delete('getlocations_fields_entities')
    ->condition('glid', $glid)
    ->execute();

}

/**
 * Create a location
 * @param array $location
 *  The location
 *
 * @param array $relations
 *  Relationship information
 *
 */
function getlocations_fields_delete_revision_record($location, $relations) {

  if (isset($location['glid']) && $location['glid'] ) {
    $glid = $location['glid'];
    getlocations_fields_delete_revision_record_relations($relations, $glid);

    // now see if there are any left for glid
    $query = db_select('getlocations_fields', 'f');
    $query->fields('e', array('nid', 'vid', 'uid', 'tid', 'cid'));
    $query->join('getlocations_fields_entities', 'e', 'f.glid=e.glid');
    $query->condition('e.glid', $glid);
    $rows = $query->execute();
    $ct = 0;
    foreach ($rows AS $row) {
      if ($row->nid || $row->vid || $row->uid || $row->tid || $row->cid ) {
        $ct++;
      }
    }
    if (! $ct) {
      db_delete('getlocations_fields')
        ->condition('glid', $glid)
        ->execute();
    }
  }
}

/**
 * @param array $relations
 *  Relationship information
 *
 * @param int $glid
 *  The location ID
 *
 */
function getlocations_fields_delete_revision_record_relations($relations, $glid) {

    $query = db_delete('getlocations_fields_entities')
    ->condition('glid', $glid);
    foreach ($relations AS $key => $value) {
      $query->condition($key, $value);
    }
    $query->execute();

}

/**
 * @param int $id
 *  Primary identifier of the content type the location is linked to
 *
 * @param string $key
 *  The name of the primary identifier
 *
 * @return array $locations
 *  The locations associated with the content type
 *
 */
function getlocations_fields_load_locations($id, $key = 'vid', $field_name = '') {
  // $key can be vid, nid, uid, tid, cid
  $locations = array();
  if ($id) {
    module_load_include('inc', 'getlocations_fields', 'getlocations_fields.functions');
    $getlocations_fields_defaults = getlocations_fields_defaults();
    $query = db_select('getlocations_fields', 'f');
    $query->fields('f', array('glid', 'name', 'street', 'additional', 'city', 'province', 'postal_code', 'country', 'address', 'latitude', 'longitude', 'marker'));
    $query->fields('e', array('nid', 'uid', 'tid', 'cid', 'field_name'));
    $query->join('getlocations_fields_entities', 'e', 'f.glid=e.glid');
    if ($field_name) {
      $query->join('field_config', 'c', 'e.field_name = c.field_name');
      $query->condition('e.field_name', $field_name);
    }
    $query->condition('e.' . $key, $id);
    $rows = $query->execute();
    $ct = 0;
    foreach ($rows AS $row) {
      $locations[$ct]['glid'] = $row->glid;
      $locations[$ct]['lid'] = $row->glid;
      $locations[$ct]['name'] = $row->name;
      $locations[$ct]['street'] = $row->street;
      $locations[$ct]['additional'] = $row->additional;
      $locations[$ct]['city'] = $row->city;
      $locations[$ct]['province'] = $row->province;
      $locations[$ct]['province_name'] = $row->province;
      $locations[$ct]['postal_code'] = $row->postal_code;
      if ($getlocations_fields_defaults['country_full'] && drupal_strlen($row->country) == 2) {
        $location[$ct]['country_name'] = getlocations_get_country_name($row->country);
      }
      else {
        $location[$ct]['country_name'] = $row->country;
      }
      $locations[$ct]['country'] = $row->country;
      $locations[$ct]['address'] = $row->address;
      $locations[$ct]['latitude'] = $row->latitude;
      $locations[$ct]['longitude'] = $row->longitude;
      $locations[$ct]['marker'] = $row->marker;
      $locations[$ct]['nid'] = $row->nid;
      $locations[$ct]['uid'] = $row->uid;
      $locations[$ct]['tid'] = $row->tid;
      $locations[$ct]['cid'] = $row->cid;
      $locations[$ct]['field_name'] = $row->field_name;
      if ($row->nid) {
        $locations[$ct]['type'] = 'node';
      }
      elseif ($row->uid) {
        $locations[$ct]['type'] = 'user';
      }
      elseif ($row->tid) {
        $locations[$ct]['type'] = 'vocabulary';
      }
      elseif ($row->cid) {
        $locations[$ct]['type'] = 'comment';
      }
      $ct++;
    }
  }

  return $locations;
}

/**
 * @param int $glid
 *  Location ID
 */
function getlocations_fields_load_location($glid) {
  $location = array();
  if ($glid) {
    module_load_include('inc', 'getlocations_fields', 'getlocations_fields.functions');
    $getlocations_fields_defaults = getlocations_fields_defaults();
    $query = db_select('getlocations_fields', 'f');
    $query->fields('f', array('glid', 'name', 'street', 'additional', 'city', 'province', 'postal_code', 'country', 'address', 'latitude', 'longitude', 'marker'));
    $query->fields('e', array('nid', 'uid', 'tid', 'cid'));
    $query->join('getlocations_fields_entities', 'e', 'f.glid=e.glid');
    $query->condition('f.glid', $glid);
    $row = $query->execute()->fetchObject();
    if ($row) {
      $location['glid'] = $row->glid;
      $location['lid'] = $row->glid;
      $location['name'] = $row->name;
      $location['street'] = $row->street;
      $location['additional'] = $row->additional;
      $location['city'] = $row->city;
      $location['province'] = $row->province;
      $location['province_name'] = $row->province;
      $location['postal_code'] = $row->postal_code;
      if ($getlocations_fields_defaults['country_full'] && drupal_strlen($row->country) == 2) {
        $location['country_name'] = getlocations_get_country_name($row->country);
      }
      else {
        $location['country_name'] = $row->country;
      }
      $location['country'] = $row->country;
      $location['address'] = $row->address;
      $location['latitude'] = $row->latitude;
      $location['longitude'] = $row->longitude;
      $location['marker'] = $row->marker;
      $location['nid'] = $row->nid;
      $location['uid'] = $row->uid;
      $location['tid'] = $row->tid;
      $location['cid'] = $row->cid;
      if ($row->nid) {
        $location['type'] = 'node';
      }
      elseif ($row->uid) {
        $location['type'] = 'user';
      }
      elseif ($row->tid) {
        $location['type'] = 'vocabulary';
      }
      elseif ($row->cid) {
        $location['type'] = 'comment';
      }
    }
  }
  return $location;
}

/**
 * @param array $defaults
 *  Settings
 *
 * @param string $mapid
 *  Unique map identifier used in javascript to allow multiple maps
 *
 */
function getlocations_fields_js_settings_do($defaults, $mapid) {

  $settings = array(
    $mapid => array(
      'nodezoom' => $defaults['nodezoom'],
      'map_marker' => $defaults['input_map_marker'],
      'use_address' => $defaults['use_address'],
      'latlon_warning' => $defaults['latlon_warning'],
      'autocomplete_bias' => $defaults['autocomplete_bias'],
      'restrict_by_country' => $defaults['restrict_by_country'],
      'search_country' => $defaults['search_country'],
    ),
  );

  drupal_add_js(array('getlocations_fields' => $settings), 'setting');

}

/**
 * @return array $defaults
 *  Settings
 */
function getlocations_fields_defaults() {
  $getlocations_defaults = getlocations_defaults();
  $defaults = array(
    'country'                         => variable_get('site_default_country', ''),
    'display_mapwidth'                => $getlocations_defaults['width'],
    'display_mapheight'               => $getlocations_defaults['height'],
    'nodezoom'                        => $getlocations_defaults['nodezoom'],
    'map_backgroundcolor'             => $getlocations_defaults['map_backgroundcolor'],
    'display_showmap'                 => 1,
    'display_maplink'                 => 1,
    'display_latlong'                 => 1,
    'display_dms'                     => 0,
    'display_onemap'                  => 0,
    'display_name'                    => 1,
    'display_street'                  => 1,
    'display_additional'              => 1,
    'display_city'                    => 1,
    'display_province'                => 1,
    'display_postal_code'             => 1,
    'display_country'                 => 1,
    'country_full'                    => 1,
    'use_address'                     => 1,
    'input_address_width'             => 40,
    'input_name_width'                => 40,
    'input_street_width'              => 40,
    'input_additional_width'          => 40,
    'input_city_width'                => 40,
    'input_province_width'            => 40,
    'input_postal_code_width'         => 40,
    'input_country_width'             => 40,
    'input_latitude_width'            => 20,
    'input_longitude_width'           => 20,
    'input_name_required'             => 0,
    'input_street_required'           => 0,
    'input_additional_required'       => 0,
    'input_city_required'             => 0,
    'input_province_required'         => 0,
    'input_postal_code_required'      => 0,
    'input_country_required'          => 0,
    'input_name_weight'               => 0,
    'input_street_weight'             => 0,
    'input_additional_weight'         => 0,
    'input_city_weight'               => 0,
    'input_province_weight'           => 0,
    'input_postal_code_weight'        => 0,
    'input_country_weight'            => 0,
    'input_latitude_weight'           => 0,
    'input_longitude_weight'          => 0,
    'input_map_weight'                => 0,
    'input_marker_weight'             => 0,
    'input_geobutton_weight'          => 0,
    'input_smart_ip_button_weight'    => 0,
    'input_geolocation_button_weight' => 0,
    'use_smart_ip_button'             => 0,
    'use_geolocation_button'          => 0,
    'use_country_dropdown'            => 1,
    'only_continents'                 => '',
    'only_countries'                  => '',
    'province_autocomplete'           => 0,
    'city_autocomplete'               => 0,
    'per_item_marker'                 => 0,
    'latlon_warning'                  => 0,
    'autocomplete_bias'               => 0,
    'restrict_by_country'             => 0,
    'search_country'                  => variable_get('site_default_country', ''),
    'use_smart_ip_latlon'             => 0,
    'columns'                         => array(
      'glid'        => t('Glid'),
      'name'        => t('Name'),
      'street'      => t('Street'),
      'additional'  => t('Additional'),
      'city'        => t('City'),
      'province'    => t('Province'),
      'postal_code' => t('Post code'),
      'country'     => t('Country'),
      'latitude'    => t('Latitude'),
      'longitude'   => t('Longitude'),
      'marker'      => t('Marker'),
    ),
  );

  $getlocations_fields_defaults = variable_get('getlocations_fields_defaults', $defaults);
  $newdefaults = getlocations_adjust_vars($defaults, $getlocations_fields_defaults);
  return $newdefaults;
}

/**
 * @return array $defaults
 *  Settings for the Field module
 */
function getlocations_fields_field_info_defaults() {
  $getlocations_defaults = getlocations_defaults();
  $getlocations_fields_defaults = getlocations_fields_defaults();
  $defaults = array(
    'getlocations_fields' => array(
      'label' => t('Getlocations Fields'),
      'description' => t('Provide Getlocations Fields.'),
      'default_formatter' => 'getlocations_fields_default',
      'default_widget' => 'getlocations_fields',
      'settings' => array(
        'mapwidth'                        => $getlocations_defaults['width'],
        'mapheight'                       => $getlocations_defaults['height'],
        'latlong'                         => $getlocations_defaults['latlong'],
        'zoom'                            => $getlocations_defaults['zoom'],
        'controltype'                     => $getlocations_defaults['controltype'],
        'pancontrol'                      => $getlocations_defaults['pancontrol'],
        'mtc'                             => $getlocations_defaults['mtc'],
        'maptype'                         => $getlocations_defaults['maptype'],
        'baselayers'                      => $getlocations_defaults['baselayers'],
        'behavior'                        => $getlocations_defaults['behavior'],
        'draggable'                       => $getlocations_defaults['draggable'],
        'map_marker'                      => $getlocations_defaults['node_map_marker'],
        'node_map_marker'                 => $getlocations_defaults['node_map_marker'],
        'user_map_marker'                 => $getlocations_defaults['user_map_marker'],
        'vocabulary_map_marker'           => $getlocations_defaults['vocabulary_map_marker'],
        'comment_map_marker'              => $getlocations_defaults['comment_map_marker'],
        'input_map_marker'                => $getlocations_defaults['input_map_marker'],
        'use_address'                     => $getlocations_fields_defaults['use_address'],
        'input_address_width'             => $getlocations_fields_defaults['input_address_width'],
        'input_name_width'                => $getlocations_fields_defaults['input_name_width'],
        'input_street_width'              => $getlocations_fields_defaults['input_street_width'],
        'input_additional_width'          => $getlocations_fields_defaults['input_additional_width'],
        'input_city_width'                => $getlocations_fields_defaults['input_city_width'],
        'input_province_width'            => $getlocations_fields_defaults['input_province_width'],
        'input_postal_code_width'         => $getlocations_fields_defaults['input_postal_code_width'],
        'input_country_width'             => $getlocations_fields_defaults['input_country_width'],
        'input_latitude_width'            => $getlocations_fields_defaults['input_latitude_width'],
        'input_longitude_width'           => $getlocations_fields_defaults['input_longitude_width'],
        'input_name_required'             => $getlocations_fields_defaults['input_name_required'],
        'input_street_required'           => $getlocations_fields_defaults['input_street_required'],
        'input_additional_required'       => $getlocations_fields_defaults['input_additional_required'],
        'input_city_required'             => $getlocations_fields_defaults['input_city_required'],
        'input_province_required'         => $getlocations_fields_defaults['input_province_required'],
        'input_postal_code_required'      => $getlocations_fields_defaults['input_postal_code_required'],
        'input_country_required'          => $getlocations_fields_defaults['input_country_required'],
        'input_name_weight'               => $getlocations_fields_defaults['input_name_weight'],
        'input_street_weight'             => $getlocations_fields_defaults['input_street_weight'],
        'input_additional_weight'         => $getlocations_fields_defaults['input_additional_weight'],
        'input_city_weight'               => $getlocations_fields_defaults['input_city_weight'],
        'input_province_weight'           => $getlocations_fields_defaults['input_province_weight'],
        'input_postal_code_weight'        => $getlocations_fields_defaults['input_postal_code_weight'],
        'input_country_weight'            => $getlocations_fields_defaults['input_country_weight'],
        'input_map_weight'                => $getlocations_fields_defaults['input_map_weight'],
        'input_marker_weight'             => $getlocations_fields_defaults['input_marker_weight'],
        'input_latitude_weight'           => $getlocations_fields_defaults['input_latitude_weight'],
        'input_longitude_weight'          => $getlocations_fields_defaults['input_longitude_weight'],
        'input_geobutton_weight'          => $getlocations_fields_defaults['input_geobutton_weight'],
        'input_smart_ip_button_weight'    => $getlocations_fields_defaults['input_smart_ip_button_weight'],
        'input_geolocation_button_weight' => $getlocations_fields_defaults['input_geolocation_button_weight'],
        'use_smart_ip_button'             => $getlocations_fields_defaults['use_smart_ip_button'],
        'use_country_dropdown'            => $getlocations_fields_defaults['use_country_dropdown'],
        'only_continents'                 => $getlocations_fields_defaults['only_continents'],
        'only_countries'                  => $getlocations_fields_defaults['only_countries'],
        'province_autocomplete'           => $getlocations_fields_defaults['province_autocomplete'],
        'city_autocomplete'               => $getlocations_fields_defaults['city_autocomplete'],
        'country'                         => $getlocations_fields_defaults['country'],
        'per_item_marker'                 => $getlocations_fields_defaults['per_item_marker'],
        'latlon_warning'                  => $getlocations_fields_defaults['latlon_warning'],
        'use_geolocation_button'          => $getlocations_fields_defaults['use_geolocation_button'],
        'autocomplete_bias'               => $getlocations_fields_defaults['autocomplete_bias'],
        'restrict_by_country'             => $getlocations_fields_defaults['restrict_by_country'],
        'search_country'                  => $getlocations_fields_defaults['search_country'],
        'map_backgroundcolor'             => $getlocations_fields_defaults['map_backgroundcolor'],
        'use_smart_ip_latlon'             => $getlocations_fields_defaults['use_smart_ip_latlon'],
      ),
    ),
  );

  return $defaults;

}

/**
 * @return array $defaults
 *  Settings for the Field formatter
 */
function getlocations_fields_field_formatter_info_defaults() {
  $getlocations_defaults = getlocations_defaults();
  $getlocations_fields_defaults = getlocations_fields_defaults();

  $defaults = array(
    'display_mapwidth'      => $getlocations_defaults['width'],
    'display_mapheight'     => $getlocations_defaults['height'],
    'display_showmap'       => $getlocations_fields_defaults['display_showmap'],
    'display_maplink'       => $getlocations_fields_defaults['display_maplink'],
    'display_latlong'       => $getlocations_fields_defaults['display_latlong'],
    'display_dms'           => $getlocations_fields_defaults['display_dms'],
    'display_onemap'        => $getlocations_fields_defaults['display_onemap'],
    'controltype'           => $getlocations_defaults['controltype'],
    'pancontrol'            => $getlocations_defaults['pancontrol'],
    'mtc'                   => $getlocations_defaults['mtc'],
    'maptype'               => $getlocations_defaults['maptype'],
    'baselayers'            => $getlocations_defaults['baselayers'],
    'behavior'              => $getlocations_defaults['behavior'],
    'draggable'             => $getlocations_defaults['draggable'],
    'streetview_show'       => $getlocations_defaults['streetview_show'],
    'trafficinfo'           => $getlocations_defaults['trafficinfo'],
    'trafficinfo_state'     => $getlocations_defaults['trafficinfo_state'],
    'bicycleinfo'           => $getlocations_defaults['bicycleinfo'],
    'bicycleinfo_state'     => $getlocations_defaults['bicycleinfo_state'],
    'transitinfo'           => $getlocations_defaults['transitinfo'],
    'transitinfo_state'     => $getlocations_defaults['transitinfo_state'],
    'panoramio_show'        => $getlocations_defaults['panoramio_show'],
    'panoramio_state'       => $getlocations_defaults['panoramio_state'],
    'poi_show'              => $getlocations_defaults['poi_show'],
    'transit_show'          => $getlocations_defaults['transit_show'],
    'map_marker'            => $getlocations_defaults['node_map_marker'],
    'node_map_marker'       => $getlocations_defaults['node_map_marker'],
    'user_map_marker'       => $getlocations_defaults['user_map_marker'],
    'vocabulary_map_marker' => $getlocations_defaults['vocabulary_map_marker'],
    'comment_map_marker'    => $getlocations_defaults['comment_map_marker'],
    'markeraction'          => $getlocations_defaults['markeraction'],
    'markeractiontype'      => $getlocations_defaults['markeractiontype'],
    'weather_show'          => $getlocations_defaults['weather_show'],
    'weather_state'         => $getlocations_defaults['weather_state'],
    'weather_cloud'         => $getlocations_defaults['weather_cloud'],
    'weather_cloud_state'   => $getlocations_defaults['weather_cloud_state'],
    'map_backgroundcolor'   => $getlocations_defaults['map_backgroundcolor'],
    'display_name'          => $getlocations_fields_defaults['display_name'],
    'display_street'        => $getlocations_fields_defaults['display_street'],
    'display_additional'    => $getlocations_fields_defaults['display_additional'],
    'display_city'          => $getlocations_fields_defaults['display_city'],
    'display_province'      => $getlocations_fields_defaults['display_province'],
    'display_postal_code'   => $getlocations_fields_defaults['display_postal_code'],
    'display_country'       => $getlocations_fields_defaults['display_country'],
    'country_full'          => $getlocations_fields_defaults['country_full'],
    'per_item_marker'       => $getlocations_fields_defaults['per_item_marker'],
    'nodezoom'              => $getlocations_fields_defaults['nodezoom'],
  );
  return $defaults;

}

/**
 * input settings form for sharing
 *
 * @param array $defaults
 *  Settings
 *
 * @return array $form
 *
 */
function getlocations_fields_input_settings_form($defaults) {
  drupal_add_js(GETLOCATIONS_FIELDS_PATH . '/js/getlocations_fields_admin.js');
  drupal_add_css(GETLOCATIONS_FIELDS_PATH . '/getlocations_fields.css');

  $form = array();
  // input form defaults
  $form['use_address'] = getlocations_element_dd(
    t('Search options'),
    $defaults['use_address'],
    array('0' => t('No Search box'), '1' => t('Search box with Geocode button'), '2' => t('Search box with Automatic Geocoding')),
    t("With 'No Search box' you must fill in the address then use the Geocode button to find the location.<br />With 'Search box with Geocode button' you can fill in the Search box then use the Geocode button to find the location.<br />With 'Search box with Automatic Geocoding' the Geocoding will be done when the Search has been selected.")
  );

  $form['input_address_width'] = getlocations_element_map_tf(
    t('Search box width'),
    $defaults['input_address_width'],
    t('The width of the Google Autocomplete search textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_address_width']['#prefix'] = '<div id="wrap-input_address_width">';
  $form['input_address_width']['#suffix'] = '</div>';

  $form['autocomplete_bias'] = getlocations_element_map_checkbox(
    t('Enable Viewport bias'),
    $defaults['autocomplete_bias'],
    t('Bias the Google Autocomplete results to the area on the map.')
  );

  // country restriction
  $form['restrict_by_country'] = getlocations_element_map_checkbox(
    t('Restrict by country'),
    $defaults['restrict_by_country'],
    t('Restrict searches to the country set below. Works with Google Autocomplete. This will override all other country settings.')
  );
  $form['restrict_by_country']['#suffix'] = '<div id="getlocations_fields_search_country">';
  $form['search_country'] = getlocations_fields_element_country($defaults['search_country'], t('Search country'), FALSE);
  $form['search_country']['#suffix'] = '</div>';

  if (module_exists('smart_ip')) {
    $form['use_smart_ip_button'] = getlocations_element_map_checkbox(
      t('Provide IP based geocoding option'),
      $defaults['use_smart_ip_button'],
      t('Use Smart IP module to provide a location.')
    );
  }

  $form['use_geolocation_button'] = getlocations_element_map_checkbox(
    t('Provide Browser based geocoding option'),
    $defaults['use_geolocation_button'],
    t('Use the browser to find a location.')
  );

  $form['input_name_width'] = getlocations_element_map_tf(
    t('Name box width'),
    $defaults['input_name_width'],
    t('The width of the name textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_name_required'] = getlocations_fields_element_opts(
    t('Name box settings'),
    $defaults['input_name_required'],
    ''
  );
  $form['input_name_weight'] = getlocations_fields_element_weight(
    t('Name box position'),
    $defaults['input_name_weight'],
    ''
  );

  $form['input_street_width'] = getlocations_element_map_tf(
    t('Street box width'),
    $defaults['input_street_width'],
    t('The width of the street textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_street_required'] = getlocations_fields_element_opts(
    t('Street box settings'),
    $defaults['input_street_required'],
    ''
  );
  $form['input_street_weight'] = getlocations_fields_element_weight(
    t('Street box position'),
    $defaults['input_street_weight'],
    ''
  );

  $form['input_additional_width'] = getlocations_element_map_tf(
    t('Additional box width'),
    $defaults['input_additional_width'],
    t('The width of the additional textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_additional_required'] = getlocations_fields_element_opts(
    t('Additional box settings'),
    $defaults['input_additional_required'],
    ''
  );
  $form['input_additional_weight'] = getlocations_fields_element_weight(
    t('Additional box position'),
    $defaults['input_additional_weight'],
    ''
  );

  $form['input_city_width'] = getlocations_element_map_tf(
    t('City box width'),
    $defaults['input_city_width'],
    t('The width of the city textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_city_required'] = getlocations_fields_element_opts(
    t('City box settings'),
    $defaults['input_city_required'],
    ''
  );
  $form['input_city_weight'] = getlocations_fields_element_weight(
    t('City box position'),
    $defaults['input_city_weight'],
    ''
  );

  $form['input_province_width'] = getlocations_element_map_tf(
    t('Province box width'),
    $defaults['input_province_width'],
    t('The width of the province/county/state textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_province_required'] = getlocations_fields_element_opts(
    t('Province box settings'),
    $defaults['input_province_required'],
    ''
  );
  $form['input_province_weight'] = getlocations_fields_element_weight(
    t('Province box position'),
    $defaults['input_province_weight'],
    ''
  );

  $form['input_postal_code_width'] = getlocations_element_map_tf(
    t('Postal code box width'),
    $defaults['input_postal_code_width'],
    t('The width of the post code textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_postal_code_required'] = getlocations_fields_element_opts(
    t('Postal code box settings'),
    $defaults['input_postal_code_required'],
    ''
  );
  $form['input_postal_code_weight'] = getlocations_fields_element_weight(
    t('Post code box position'),
    $defaults['input_postal_code_weight'],
    ''
  );

  $form['input_latitude_width'] = getlocations_element_map_tf(
    t('Latitude box width'),
    $defaults['input_latitude_width'],
    t('The width of the latitude textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_latitude_weight'] = getlocations_fields_element_weight(
    t('Latitude box position'),
    $defaults['input_latitude_weight'],
    ''
  );
  $form['input_longitude_width'] = getlocations_element_map_tf(
    t('Longitude box width'),
    $defaults['input_longitude_width'],
    t('The width of the longitude textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_longitude_weight'] = getlocations_fields_element_weight(
    t('Longitude box position'),
    $defaults['input_longitude_weight'],
    ''
  );
  $form['input_map_weight'] = getlocations_fields_element_weight(
    t('Map position'),
    $defaults['input_map_weight'],
    ''
  );
  $form['input_geobutton_weight'] = getlocations_fields_element_weight(
    t('Geocode button position'),
    $defaults['input_geobutton_weight'],
    ''
  );

  if (module_exists('smart_ip')) {
    $form['input_smart_ip_button_weight'] = getlocations_fields_element_weight(
      t('Smart IP button position'),
      $defaults['input_smart_ip_button_weight'],
      ''
    );
  }

  $form['input_geolocation_button_weight'] = getlocations_fields_element_weight(
    t('Geolocation button position'),
    $defaults['input_geolocation_button_weight'],
    ''
  );

  $form['input_country_width'] = getlocations_element_map_tf(
    t('Country box width'),
    $defaults['input_country_width'],
    t('The width of the country textbox. Must be a positive number.'),
    10,
    10,
    TRUE
  );
  $form['input_country_required'] = getlocations_fields_element_opts(
    t('Country box settings'),
    $defaults['input_country_required'],
    ''
  );
  $form['input_country_weight'] = getlocations_fields_element_weight(
    t('Country box position'),
    $defaults['input_country_weight'],
    ''
  );

  // city_autocomplete
  $form['city_autocomplete'] = getlocations_element_dd(
    t('City input method'),
    $defaults['city_autocomplete'],
    array(
      0 => t('Normal textfield'),
      1 => t('Autocomplete'),
    ),
    t('Autocomplete works on existing records so it works best if you already have some.')
  );

  // province_autocomplete
  $form['province_autocomplete'] = getlocations_element_dd(
    t('Province/State/County input method'),
    $defaults['province_autocomplete'],
    array(
      0 => t('Normal textfield'),
      1 => t('Autocomplete'),
    ),
    t('Autocomplete works on existing records so it works best if you already have some.')
  );

  $form['country'] = getlocations_fields_element_country($defaults['country'], t('Default country'), FALSE);

  // country dropdown
  $form['use_country_dropdown'] = getlocations_element_dd(
    t('Country input method'),
    $defaults['use_country_dropdown'],
    array(
      0 => t('Normal textfield'),
      1 => t('Dropdown'),
      2 => t('Autocomplete'),
    )
  );

  if (module_exists('countries')) {
    $continents = variable_get('countries_continents', countries_get_default_continents());
    unset($continents['UN']);
    $form['only_continents'] = getlocations_element_dd(
      t('Limit to Continents'),
      $defaults['only_continents'],
      $continents,
      t('Limit to Continents only applies to Country dropdown.'),
      TRUE
    );
    $form['only_countries'] = getlocations_element_map_tf(
      t('Limit to Countries'),
      $defaults['only_countries'],
      t('Limit to Countries only applies to Country dropdown. This should be a comma delimited list of two letter ISO codes, no spaces.'),
      30,
      255
    );
  }

  // per_item_marker
  $form['per_item_marker'] = getlocations_element_map_checkbox(
    t('Allow per item markers'),
    $defaults['per_item_marker'],
    t('Allow each item to have a marker selected.')
  );
  $form['input_marker_weight'] = getlocations_fields_element_weight(
    t('Marker select position'),
    $defaults['input_marker_weight'],
    ''
  );

  // latlon_warning
  $form['latlon_warning'] = getlocations_element_map_checkbox(
    t('Enable empty lat/lon popup warning'),
    $defaults['latlon_warning'],
    t('Enables a javascript popup that warns users that they have not geocoded the address. Only use this if you have a fixed number of addresses.')
  );

  return $form;

}

/**
 * display settings form for sharing
 *
 * @param array $defaults
 *  Settings
 *
 * @return array $form
 *
 */
function getlocations_fields_display_settings_form($defaults) {

  $form = array();

  // display defaults
  $form['display_showmap'] = getlocations_element_map_checkbox(
    t('Show map in display'),
    $defaults['display_showmap'],
    ''
  );
  $form['display_maplink'] = getlocations_element_map_checkbox(
    t('Show link to map in display'),
    $defaults['display_maplink'],
    t('Only applicable when the map is not being displayed.')
  );
  $form['display_mapwidth'] = getlocations_element_map_tf(
    t('Map width'),
    $defaults['display_mapwidth'],
    t('The width of a Google map, as a CSS length or percentage. Examples: <em>50px</em>, <em>5em</em>, <em>2.5in</em>, <em>95%</em>'),
    10,
    10,
    TRUE
  );
  $form['display_mapheight'] = getlocations_element_map_tf(
    t('Map height'),
    $defaults['display_mapheight'],
    t('The height of a Google map, as a CSS length or percentage. Examples: <em>50px</em>, <em>5em</em>, <em>2.5in</em>, <em>95%</em>'),
    10,
    10,
    TRUE
  );
  $form['display_latlong'] = getlocations_element_map_checkbox(
    t('Show Latitude/Longitude in display'),
    $defaults['display_latlong'],
    ''
  );
  $form['display_dms'] = getlocations_element_map_checkbox(
    t('Show Latitude/Longitude in Degrees, minutes, seconds'),
    $defaults['display_dms'],
    ''
  );

  $form['display_onemap'] = getlocations_element_map_checkbox(
    t('Show all markers on one map'),
    $defaults['display_onemap'],
    ''
  );

  $form['display_name'] = getlocations_element_map_checkbox(
    t('Show Name in display'),
    $defaults['display_name'],
    ''
  );
  $form['display_street'] = getlocations_element_map_checkbox(
    t('Show Street in display'),
    $defaults['display_street'],
    ''
  );
  $form['display_additional'] = getlocations_element_map_checkbox(
    t('Show Additional in display'),
    $defaults['display_additional'],
    ''
  );
  $form['display_city'] = getlocations_element_map_checkbox(
    t('Show City in display'),
    $defaults['display_city'],
    ''
  );
  $form['display_province'] = getlocations_element_map_checkbox(
    t('Show Province/state/county in display'),
    $defaults['display_province'],
    ''
  );
  $form['display_postal_code'] = getlocations_element_map_checkbox(
    t('Show Postal code in display'),
    $defaults['display_postal_code'],
    ''
  );
  $form['display_country'] = getlocations_element_map_checkbox(
    t('Show Country in display'),
    $defaults['display_country'],
    ''
  );
  $form['country_full'] = getlocations_element_map_checkbox(
    t('Display full country name'),
    $defaults['country_full'],
    ''
  );
  $form['nodezoom'] = getlocations_element_map_zoom(
    t('Zoom'),
    $defaults['nodezoom'],
    t('The zoom level for a display map.')
  );

  return $form;

}

/**
 * Implements hook_modules_uninstalled().
 *
 * Cleans up entries related to taxonomy or comment modules
 */

function getlocations_fields_modules_uninstalled($modules) {

  $identifier = '';
  foreach ($modules as $module) {
    if ($module == 'taxonomy') {
      $identifier = 'tid';
    }
    elseif ($module == 'comment') {
      $identifier = 'cid';
    }
    elseif ($module == 'profile2') {
      $identifier = 'uid';
    }

    if ($identifier) {
      $instances = array();
      // field_info_instances() is unuseable so roll our own
      $query = db_select('field_config', 'f');
      $query->fields('i', array('field_name', 'entity_type', 'bundle'));
      $query->join('field_config_instance', 'i', 'f.id=i.field_id');
      $query->condition('f.module', 'getlocations_fields')
        ->condition('f.type', 'getlocations_fields')
        ->condition('i.entity_type', $module);
      $result = $query->execute();
      if ($result) {
        $ct = 0;
        foreach ($result AS $row) {
          $instances[$ct]['field_name'] = $row->field_name;
          $instances[$ct]['entity_type'] = $row->entity_type;
          $instances[$ct]['bundle'] = $row->bundle;
          $ct++;
        }
      }
      if (count($instances)) {
        $glids = array();
        foreach ($instances AS $k => $instance) {
          $query = db_select('getlocations_fields_entities', 'e');
          $query->fields('e', array('glid'));
          $query->condition('e.' . $identifier, 0, '>')
            ->condition('e.field_name', $instance['field_name']);
          $result2 = $query->execute();
          if ($result2) {
            foreach ($result2 AS $row) {
              $glids[] = $row->glid;
            }
          }
          field_delete_instance($instance);
        }
        if (count($glids)) {
          foreach ($glids AS $glid) {
            getlocations_fields_delete_record(array('glid' => $glid), '');
          }
        }
        field_purge_batch(1000);
        // for some reason the record in field_config_instance does not get deleted
        // even though it is set to be deleted, so do it now.
        db_delete('field_config_instance')->condition('entity_type', $module)->execute();
      }
    }
  }
}

// backward compat
function getlocations_fields_get_countries_list($upper = TRUE) {
  $countries = getlocations_get_countries_list($upper);
  return $countries;
}
